#include "totvs.ch"
#include "protheus.ch"

/*/{Protheus.doc} zTGet
TGet
@type function
@version  24.10
@author erikt
@since 05/07/2026
/*/
user function zTGet

    Local oDlg1
    Local oButton1
    Local oSay

    oDlg1   := TDialog():New(0, 0, 400, 400, 'Exemplo TSay', , , , , , /*nCorFundo*/, , , .T.)

    oSay    := TSay():New(05,50,{||'Texto para exibição'},oDlg1,,,,,,.T.,CLR_RED,CLR_WHITE,200,20)

    oButton1 := TButton():New(80,10, "Executar", oDlg1, { || oDlg1:End() }, 60, 15,,,.F., .T., .F.,, .F.,,, .F.)

    oDlg1:Activate()

return

